# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - vajra_arm_controller
    - vajra_arm

  vajra_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - Base
      - Link_1_joint
      - Link_2_joint
      - Link_2_roll_joint
    action_ns: follow_joint_trajectory
    default: true
  vajra_arm:
    type: GripperCommand
    joints:
      - Link_3_joint
    action_ns: gripper_cmd
    default: true